pref("extensions.sstart.thumbnail.width", 286);
pref("extensions.sstart.thumbnail.height", 222);
pref("extensions.sstart.gridInterval", 32);
pref("extensions.sstart.backgroundStyle", 1);
pref("extensions.sstart.focus", "");
pref("extensions.sstart.showDecorations", true);
pref("extensions.sstart.overrideNewTab", true);
pref("extensions.sstart.overrideHomePage", false);
pref("extensions.sstart.newtabOnLockDrag", true);
